insert into CAR (ID, HORSEPOWER, MODEL, OWNER_ID) VALUES ( 1, 10, 'BMW-X14',1);
insert into CAR (ID, HORSEPOWER, MODEL, OWNER_ID) VALUES ( 2, 10, 'BMX-X14',1);
insert into CAR (ID, HORSEPOWER, MODEL, OWNER_ID) VALUES ( 3, 10, 'BMW-X45',1);